# Generation settings
FOOD_PER_WEEK = 4
EXTRA_PER_WEEK = 1
TYPE_COOLDOWN = 0
PROTEIN_COOLDOWN = 0
FOOD_COOLDOWN = 5
FOOD_STORAGE = "ruoat"

# Bot settings
POLL_INTERVAL_SECONDS = 5
STARTUP_NEWNESS_MINUTES = 10

FOOD_COMMAND = "r".lower()
EXTRA_COMMAND = "e".lower()
RELOAD_COMMAND = "reload".lower()
RERANDOMIZE_COMMAND = "generoi!".lower()

SPREADSHEET_ID = '1WtZZpOU506_iPujD4uJhGOa20jv1daNtYaqKdz47x0A'
RANGE_NAME = 'Arki'
